version: '3'
services:
  loadbalancer:
    build: .
    ports:
      - "${LB_PORT:-8080}:8080"
    command: ["./lb"]
    environment:
      - BACKEND_URLS=http://backend1:8081,http://backend2:8082

  backend1:
    build: .
    command: ["./be", "8081"]

  backend2:
    build: .
    command: ["./be", "8082"]