version: '3'
services:
  loadbalancer:
    build: .
    ports:
      - "8080:8080"
      - "8443:8443"
    command: ["./lb"]
    environment:
      - BACKEND_URLS=http://backend1:8081,http://backend2:8082
    volumes:
      - ./server.crt:/root/server.crt
      - ./server.key:/root/server.key

  backend1:
    build: .
    command: ["./be", "8081"]

  backend2:
    build: .
    command: ["./be", "8082"]